### PR TITLE
Actually use xml-namespaces to resolve cura-ns.

### PR DESCRIPTION
**Pull request by rburema**
(Hopefully) fixes: https://github.com/Ultimaker/Cura/issues/6922

The downside of the current approach it that it retrieves the entire namespace scope from the ancestors for each altered setting. (Not exactly what you'd call optimised.) It's expected that this will be negligible compared to parsing the actual mesh in practice though, and will do fine for now.

CURA-7120

### CODE REVIEW

**Comment by Ghostkeeper** [comment]
It's not liking these tests in my build system. I get this error:

```
[100%] Linking CXX executable NamespaceTest
/usr/bin/ld: CMakeFiles/NamespaceTest.dir/tests/NamespaceTest.cpp.o: in function `xml_namespace::NamespaceTest_getAncestralNamespaces_Test::TestBody()':
NamespaceTest.cpp:(.text+0x188): undefined reference to `xml_namespace::getAncestralNamespaces[abi:cxx11](pugi::xml_node const&)'
/usr/bin/ld: NamespaceTest.cpp:(.text+0x601): undefined reference to `xml_namespace::getAncestralNamespaces[abi:cxx11](pugi::xml_node const&)'
/usr/bin/ld: NamespaceTest.cpp:(.text+0xb75): undefined reference to `xml_namespace::getAncestralNamespaces[abi:cxx11](pugi::xml_node const&)'
/usr/bin/ld: NamespaceTest.cpp:(.text+0x1023): undefined reference to `xml_namespace::getAncestralNamespaces[abi:cxx11](pugi::xml_node const&)'
/usr/bin/ld: NamespaceTest.cpp:(.text+0x161f): undefined reference to `xml_namespace::getAncestralNamespaces[abi:cxx11](pugi::xml_node const&)'
/usr/bin/ld: CMakeFiles/NamespaceTest.dir/tests/NamespaceTest.cpp.o:NamespaceTest.cpp:(.text+0x1c71): more undefined references to `xml_namespace::getAncestralNamespaces[abi:cxx11](pugi::xml_node const&)' follow
/usr/bin/ld: CMakeFiles/NamespaceTest.dir/tests/NamespaceTest.cpp.o: in function `xml_namespace::NamespaceTest_getNamesFor_Test::TestBody()':
NamespaceTest.cpp:(.text+0x4787): undefined reference to `xml_namespace::getNamesFor(std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: NamespaceTest.cpp:(.text+0x4951): undefined reference to `xml_namespace::getNamesFor(std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
```

Is there something I need to change? The namespace seems to have the same name, so I'd expect that you wouldn't even need to specify the namespace in the test and that it shouldn't fail (especially not in the linker).

**Comment by rburema** [comment]
> It's not liking these tests in my build system. I get this error:

I got the same error on the build system until I linked everything statically (see the 'compile statically' commit). I think you need to re-run cmake for that first though.

**Comment by Ghostkeeper** [comment]
After some poking around I found that these two functions can't be used externally since they are not exported. Conceivably you'd want to use those namespace functions externally as well so I just exported them. That way our tests can also reach them.

**Comment by Ghostkeeper** [comment]
I tried loading this 3MF file: [UMS5_hexasphericon.zip](https://github.com/Ultimaker/libSavitar/files/4121483/UMS5_hexasphericon.zip)

In that file I manually changed the namespace alias in `3dmodel.model`. It defines the alias at the top:

    xmlns:blabla="http://software.ultimaker.com/xml/cura/3mf/2015/10"

And then at the bottom of that file it writes some metadata in that namespace:

    <metadata name="blabla:extruder_nr" preserve="true" type="xs:string">1</metadata>

But when loading this into Cura it's not taking the extruder yet. Do we have to change something in Cura as well?

**Comment by Ghostkeeper** [comment]
Oops, I forgot that for libSavitar I need to install it as well. I didn't put up a symlink yet on this computer. Seems to work now.

**Pull request merged**
