### PR TITLE
Do not vendor the pugixml library

### LINKED ISSUE #7: unable to use system pugixml
Hi

any option for use system pugixml instead of bundled?

when install libsavitar make some file conflicts with pugixml installed in the system

### PR DESCRIPTION
**Pull request by eli-schwartz**
This prevents trying to co-install pugixml with existing system
libraries, and also fixes the includes for pugixml.hpp to actually use
the include path added by find_package/add_subdirectory instead of a
hardcoded relative path.

Fixes #7

### CODE REVIEW

**Comment by nallath** [comment]
For our reference CURA-5226

**Comment by Ghostkeeper** [comment]
Something went wrong in Jira there so I had to delete CURA-5226 and create a new ticket. The new ticket is CURA-5300.

**Comment by MathyV** [comment]
Ran into this as you can see from the commits above running Gentoo. Applied this PR and works perfectly. Would be nice if it can be merged in the next version.

**Comment by alekseisasin** [comment]
@MathyV , I tested your pull request and result of it:
1) I can build "libpugixml-dev" on Linux and Windows and it is good. Only we need to change our Cura build script. 
2) 
After installing "sudo apt-get install libpugixml-dev" I cannot call cmake because I am missing: 
**Could not find a package configuration file provided by "pugixml" with any
  of the following names:**

If I remove find_package(pugixml REQUIRED), I trigger cmake .., "make" command works well without error. 
Is suggest to replace the find_package(pugixml REQUIRED) to something else. Maybe  CheckIncludeFile(....) if not show error of missing "pugixml". Otherwise the solution will work for you and other might have problem because of "find_package(pugixml REQUIRED)"

**Comment by eli-schwartz** [comment]
Then your pugixml installation sucks and is broken, because it misses the files usr/lib/cmake/pugixml/pugixml-config-release.cmake and usr/lib/cmake/pugixml/pugixml-config.cmake which pugixml automatically installs. Or your cmake installation sucks because it is not picking up the standard cmake files installed by system packages.

(Never mind that cmake should use the standard pkg-config instead of it's homebrew solution...)

Anyway I've got no clue whatsoever whatsoever what you're proposing instead, nor why you're addressing your comment to random people instead of me, the author of this PR.

**Comment by eli-schwartz** [comment]
Mystery solved, debian's package is broken: https://packages.debian.org/sid/amd64/libpugixml-dev/filelist

You'll need to tell cmake (using `CMAKE_MODULE_PATH` to look in this private cmake directory used exclusively by libpugixml-dev on Debian.

**Comment by LipuFei** [comment]
Hi @eli-schwartz , which linux distro are you using?

**Comment by eli-schwartz** [comment]
Arch Linux.

As mentioned in #7 (referenced in the first comment) I found this bug in the process of helping to resolve downstream bug https://bugs.archlinux.org/task/57800

**Comment by Ghostkeeper** [comment]
Apparently not. It's been decided that an external dependency makes setting up your development environment for Cura needlessly difficult. We won't be merging this then. Sorry!

**Comment by anthraxx** [comment]
WAT :scream:

**Comment by jelly** [comment]
Can't we find a compromise where it can build it from an external lib for distros but use the shipped library for Cura dev env.

**Comment by eli-schwartz** [comment]
I would assume that would involve: 

> Shall we just add this library to cura-build-environment then?

It should be sufficient to tell cmake to install arbitrary (static) libs to some custom build root, and then set the cmake module path.

I'm unsure if @Ghostkeeper's rejection means only something simple enough to be shipped directly in this precise git repository would be accepted.

**Pull request closed without merging**
