### PR TITLE
Cura 5843 follow 3mf spec

### PR DESCRIPTION
**Pull request by rburema**

### CODE REVIEW

**Comment by ChrisTerBeke** [comment]
Shall we add some tests to this? It's a very isolated piece of code that can be tested easily.

**Comment by rburema** [comment]
That... is a good point. I made a sticky on the CC board so it'll be discussed tomorrow :-)

**Comment by rburema** [comment]
@ChrisTerBeke I'll (try to) work on tests in a separate PR. (If've got some time boxed for UnitTests this afternoon.)

**Comment by nallath** [comment]
As long as they are tagged with the same issue nr, that's pretty much the case.

**Comment by rburema** [comment]
Normally, I'd attach them to this ticket, but as currently libSavitar doesn't have any tests _at all_ I felt it fell a bit outside of the scope of this PR. If I get to the point where I actually write tests for this ticke I'll be sure to attach the issue-nr!

**Comment by rburema** [comment]
@ChrisTerBeke See #11 :-)

**Pull request merged**
